---
apiVersion: v1alpha1
kind: DHCPv6Config
name: eno1
---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: fd03:869b:8f3e::1
---
apiVersion: v1alpha1
kind: TimeSyncConfig
ntp:
  servers:
    - fd03:869b:8f3e::1
