apiVersion: v1
kind: Secret
metadata:
    name: openwebui-db-credentials
    namespace: prod
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:9rD3NUlLi7QEG3PlvRxVse3VBqGeP7U8ZTTFDDSF1eAwgz0Z4nhrZ891g8XUkwsz28F6g9DZPGRw3kSZNdX+rthGvviA6qg4Two+3ueILIkhcXKfzZqIfIksyUuYHXtXeEFyeu6sAFYwF1KXX/w0FSVNLzA=,iv:xT0MSbC+3NUXl5fJuZ2OL6g5gGZUDYlaoTTboI7x+DA=,tag:zYYCPlRFjigbQOFxRQIQEA==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUWpiVE9oV1F6TzhOWjdY
            eURHbDhHOW1RWjN2QUJSanp0QitsRUNwajFvClc3aXhMY2w1dnFKTkxSZnVMS1h5
            MndkT2l0SmYzaytRQ1hSVXl0RTRCMjAKLS0tIFZmTFVGdHAvcy93d2YyM2VsRTN3
            aG4ybnVDVjNRRm1Db3RqUXQ3YUtjTncKzKbqKdl3Xg34KQYENTQWaWy7HUfAmbz7
            Uw9leBf/5P7hbM2KWaU6kQFweqjUGPkcDedXHCFec1gZ6FXrsmLOtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T10:43:57Z"
    mac: ENC[AES256_GCM,data:58F/kYUyuT6eyszxSyv5sR3H7p2ymKj8+BBTIVrMIMgkBYJ68Qx5TI4eXYu6dMMew/vj/bUEf717yRyKNNYqN1JwK7S+tM6m3aha+E1BQ1E35RBttdIlfrAgQFeYnTcCTT7lsSfTJ2HQpBfK5M+VaFEIMTrX60DiYN7lRbcOXac=,iv:5jQiGij3dYQCbgonlnx8tMPMYQXfLJAsV8V8dh0xSv8=,tag:4MHygCfZ03rYUEyrw75Dvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
