---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: open-webui
      version: "13.0.1"
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
      interval: 12h
  values:
    replicaCount: 1
    ollama:
      enabled: false
    pipelines:
      enabled: false
    ingress:
      enabled: false
    service:
      type: ClusterIP
      ports:
        webui:
          port: 8080
          targetPort: 8080
    persistence:
      enabled: true
      size: 10Gi
      storageClass: iscsi
      accessModes:
        - ReadWriteOnce
    extraEnvVars:
      - name: WEBUI_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: openwebui-credentials
            key: WEBUI_SECRET_KEY
      - name: ENABLE_DB_MIGRATIONS
        value: "true"
      - name: DEFAULT_USER_ROLE
        value: "user"
