apiVersion: v1
kind: Secret
metadata:
    name: openwebui-credentials
    namespace: prod
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:0IRdEiuQTf00TqzsUVEgjHKYVmqLarnMxanaW7j8UuUGjFNhU2FDvwg4Ih8=,iv:7aP6yp6joatjPmZL+z/WlPp+pXFniGFvwMK3Rgn3tGI=,tag:2xjKSMnxplD5xKOFIHnyAQ==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbVlaanlMWHlBYjJ2MGVx
            MGpqckNDRnNuTDBlbXZtQlJwcWJJdTFXZ2hRCmVJNEc5eTdmUjhNblBpVE9CQlR0
            dklSdk5EaUZNQU9HUVlrT0pKcG8vOFEKLS0tIFhEWTBwZ2pBalVnQkx4bytKOEx2
            M0pVbXV4VUh0SWJ0RFkzNFFxbzArRHcK9I08Z5xHxni/VG9CMozEN6RqYLq8deCA
            yu6VD2xRtSrccepcFs4Jbs3D1Lqu9AgxlpqZlq4pGUSL2Qgb4qBGRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T14:33:08Z"
    mac: ENC[AES256_GCM,data:w/qk/uzVTfzVk5afhhIgb/mUmEw3/qmhoE5dYFnPTeg9JJ6liqMyqOxgZAxtAErphQsTf9nU/PWU2lY4UZu7MWBOSQ17ysW/I8oJfUpQIyL/YlMP/vMwiysW8Vpk7OdCwgdFsGxxwqjAn6WICSGP6jg4sWAXXGkSW+actZAqJO0=,iv:WUaMIPM2I97C5wuAun3Zh2AO/cQLTaYptqW7bVrrzqI=,tag:IaBM8y40DznEvbinMlN/cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
