# Encrypt before committing: sops -e -i secret.sops.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: nut-monitor-config
  namespace: kube-system
stringData:
  upsmon.conf: |
    MONITOR tower-ups@10.7.0.1 1 upsmon swXoX6vIkf0j6F0 slave
    MINSUPPLIES 1
    SHUTDOWNCMD "echo o > /proc/sysrq-trigger"
    POLLFREQ 5
    POLLFREQALERT 5
    HOSTSYNC 15
    DEADTIME 15
    POWERDOWNFLAG /etc/killpower
    FINALDELAY 5
