---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - podinfo
  - k8s-mcp-server

patches:
  - patch: |-
      - op: add
        path: /spec/targetNamespace
        value: prod
    target:
      kind: HelmRelease
