apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - fd03:869b:8f3e::200-fd03:869b:8f3e::2ff
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: ipv6-router
  namespace: metallb-system
spec:
  myASN: 64512
  peerASN: 64512
  peerAddress: fd03:869b:8f3e::1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advert
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool
