apiVersion: v1
kind: Secret
metadata:
    name: snmp-exporter-credentials
    namespace: prod
stringData:
    SNMPV3_PASS: ENC[AES256_GCM,data:UYj6nGTWWhBuI67CQZqBu3z7,iv:wQrZsGSBB7DuTiGgSIdzscVRFLjZz4Oi/zIYRJ9Nvb0=,tag:n29ECg+sEYVwCd2YEjwxHg==,type:str]
    SNMPV3_KEY: ENC[AES256_GCM,data:Wkl9UdTiQC70788VoT972cym,iv:UFVjhkdNNqG7IjiYeTjyS3eHnHHldFV3zQMDAdEw0cI=,tag:QSsLHuWoJ2kUKvVyl0tzwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b3MzQjFiOEJtWmNLWmRC
            bWpBcEROc0pvdHlEc0tIUTMzVkRISGUrT1hjCklqUDE0bnBxR0wvMXBTREhKTmli
            UzNCVU9MZVlreTQxbDNzbDNyMmYxczQKLS0tIEhoaFJoMVRYWHdZcDcxTWIreWRG
            RDJtNG9XQVlJaWRNSThxQWExaDc0b2MKqfXnU+tu7a+zx8QFOKUudKLbLs21M5A4
            BBSAK3T2Iqrcu8e0j6eh+3NOFGv+RN1niMo1a5fzhkh1jWCEslNdwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T06:16:12Z"
    mac: ENC[AES256_GCM,data:c8o7JirWMz+Mm57UFDsxmVDlq/jriTv+cZfygnRtty4k46lNMdEHFCDTajcCATBBcpwKRl2rJMlnFZnDuSGXqTHSkpLcnps51LBf2gaFFEoT6bDSxDmUYQf72O+65Bq+r7UoIBKySW6noc7m6pbyp97O6ruRx/+2Q8e8cR/BZcE=,iv:bxyHefmrjYQXrjl9ArsxdSjHv6YermuLL3wK4QLJMHM=,tag:9L+2eZGb2CYa6QQTOaAJrw==,type:str]
    version: 3.13.1
