apiVersion: v1
kind: Secret
metadata:
    name: snmp-exporter-credentials
    namespace: prod
stringData:
    OPNSENSE_SNMPV3_PASS: ENC[AES256_GCM,data:gyV3X7arK4aSHIP+5QyezyAx,iv:O1VnXVQXgohyQ5UtJgYqHvKgF1ldCV3dVQC4SeZudDY=,tag:GwB9CrqGkx+wMCA4P9jY3A==,type:str]
    OPNSENSE_SNMPV3_KEY: ENC[AES256_GCM,data:xcjK0qaTTviJxEGrPShBM4Eh,iv:TfJ/hCFqYhMM8YCiF/Ca4dyDVxzeG2Koonnan6/AUk0=,tag:eaZB1wgqrlw9bHIJ+PyuEA==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b3MzQjFiOEJtWmNLWmRC
            bWpBcEROc0pvdHlEc0tIUTMzVkRISGUrT1hjCklqUDE0bnBxR0wvMXBTREhKTmli
            UzNCVU9MZVlreTQxbDNzbDNyMmYxczQKLS0tIEhoaFJoMVRYWHdZcDcxTWIreWRG
            RDJtNG9XQVlJaWRNSThxQWExaDc0b2MKqfXnU+tu7a+zx8QFOKUudKLbLs21M5A4
            BBSAK3T2Iqrcu8e0j6eh+3NOFGv+RN1niMo1a5fzhkh1jWCEslNdwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T15:30:37Z"
    mac: ENC[AES256_GCM,data:qZP1dtN5AK6e3TFdDnoRnw8191mI3VgEF5nFk9iXPvurRc7iZeL1V5o04ufF3BdVzBi0+Ut1niJB7PPNhmQGpzM0CzttgCzsybRCRbudP7G0SEJ5iQrTcokx4MmQfgMRQl+Z06SMcCqir6fvgfjdRWlNISlOAue2qaRhwb/4DVI=,iv:vyCLBWfbZNo2Hgvob0AdUb6q6HQjNiXu+y/ggNkVC8E=,tag:fLRtJu3OynySy9YCH+4zIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
