---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - credentials.sops.yaml
  - release.yaml
  - httproute.yaml
configMapGenerator:
  - name: snmp-exporter-config
    files:
      - snmp.yaml
    options:
      disableNameSuffixHash: true
