---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snmp-exporter
  namespace: prod
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: "9.14.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 30m
  values:
    config: ""
    extraArgs: [--config.expand-environment-variables, --config.file=/config/snmp.yaml]
    envFrom:
      - secretRef:
          name: snmp-exporter-credentials
    serviceMonitor:
      enabled: true
      params:
        - name: opnsense-firewall
          target: 10.7.0.2
          module: [system, host, if_mib, opnsense]
          auth: [snmp_user]
        - name: tower
          target: 10.7.1.0
          module: [system, host, if_mib, truenas]
          auth: [snmp_user]
      metricRelabelings:
        - sourceLabels: [hrStorageType]
          regex: '1\.3\.6\.1\.2\.1\.25\.2\.1\.1'
          targetLabel: hrStorageType
          replacement: other
        - sourceLabels: [hrStorageType]
          regex: '1\.3\.6\.1\.2\.1\.25\.2\.1\.2'
          targetLabel: hrStorageType
          replacement: ram
        - sourceLabels: [hrStorageType]
          regex: '1\.3\.6\.1\.2\.1\.25\.2\.1\.3'
          targetLabel: hrStorageType
          replacement: virtualMemory
        - sourceLabels: [hrStorageType]
          regex: '1\.3\.6\.1\.2\.1\.25\.2\.1\.4'
          targetLabel: hrStorageType
          replacement: fixedDisk
        - sourceLabels: [hrStorageType]
          regex: '1\.3\.6\.1\.2\.1\.25\.2\.1\.5'
          targetLabel: hrStorageType
          replacement: removableDisk
        - sourceLabels: [hrStorageType]
          regex: '1\.3\.6\.1\.2\.1\.25\.2\.1\.9'
          targetLabel: hrStorageType
          replacement: flashMemory
        - sourceLabels: [hrStorageType]
          regex: '1\.3\.6\.1\.2\.1\.25\.2\.1\.10'
          targetLabel: hrStorageType
          replacement: networkDisk
    podAnnotations:
      checksum/snmp-config: ff2a7dbb73a39423c95ed9919044deb723fe64010e794e43fea746b6342737fe
    extraConfigmapMounts:
      - name: snmp-exporter-config
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: snmp-exporter-config
        readOnly: true
        defaultMode: 420
