apiVersion: v1
kind: Secret
metadata:
    name: truenas-api-credentials
    namespace: democratic-csi-system
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:7TNltVN+1baSHLMheH2ZeX+Ln9OQCa7QxqPckn9OHcnJiAtzNsCdyC0nbO7As91hUrVSUaH8Y5XZJcYjNJdnZMQ3,iv:xOlwPFMXaG8Y96ks1UZeCPNO8o3BrAX2mHAGRsNZ6Dc=,tag:RVC309n3uG0Rps8dqND2Mg==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQVlEbm02RCs4NkFZVzk0
            THRIQXBoYms1eTczakpleGZOZnhpYVo4SEgwClF6Z3JHUEZUQVpjYnJRNUw1T2ZB
            Nk9pbTZzWkgzamNTT2hJb2pEaVVnNGMKLS0tIEpodWc1Tm9MNWppblFYeEdKSmlI
            anl6ejdyTDdaakxFb1VndlVXOWxYVUkKwfxq/SIqjo316UU2gXEF6XGNvyFvZGvR
            iSC7wAjkTjdkiRKFhS+JmKBSgcmnMK82jPtgHlAo/fTvFrEsUTpORg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:50:52Z"
    mac: ENC[AES256_GCM,data:fl3DzSwpWvhC6oAel3zIgMoCyFKxQTA7Pzxzy8sNuCTXyFgysQKFEfS90vsyPJQ95vYdYYu4jCUjQtzsG6Pgs57fOumGjyC+Gb7qjheJp7TUK72g7bo2h95wkwWHZ6mwPFP3nmN702weHpJeibJYdYqI5P0FKBg8p9spar5VS34=,iv:Tfv/UHHi+EjvPrUt3Y5a5WLbW+uRivRzrgr0jWIQcRU=,tag:fib3u6CCM3CbDFJ1oBEgSQ==,type:str]
    encrypted_regex: ^(data|stringData|apiKey)$
    version: 3.11.0
