apiVersion: v1
kind: Secret
metadata:
    name: application-db-credentials
    namespace: prod
stringData:
    grafana-db-password: ENC[AES256_GCM,data:z1MrYdeYAMnuno3I3S69JgDy3EZA0nNsPDTpoyIyHQ==,iv:W3p78fvihUgH0IpvlZ5sCmeXOdB1SrvY+h/DGhKCuXY=,tag:Z39rDxeaCT+vbhVbj9Vo0A==,type:str]
    openwebui-db-password: ENC[AES256_GCM,data:QQBmIu3hlFJCWLeGwvvqhZGy2D5j76uXf9JgTX4/,iv:+duCFFPpkzNS4t7CQhBTw44UvHRmv7i1fnpeG8V6mOQ=,tag:/an6VYIFH/+2NkrttNwBoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Q1pveGQ2aW5hUzQrVXlw
            aU9mUEdxUkVsbkdQQXQ3bXdwQ2I0b2psOFVBClpRc242eVVyY1BhNXdrNWt3VDhh
            MXFzNTVPelNsdWR3K204UDBYYTRHeEkKLS0tICtqRFlVWVZneEtrNzlkNFVmQzNH
            V01Dc3had1owT2NQMEd6b2dnWHdwMDQKkeB8rOgaSkNB+ibEsjPc2JRpwINGOfKV
            QqhCvJzYuhzwuEg6yQW78Ax1dvf0XGE0VwLDK6WlNg7Ez2iYfSqGLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T16:09:26Z"
    mac: ENC[AES256_GCM,data:swXfDleaKg/TXaK4uAmXalbOJCacLd1UcGUmwUleIIe8oWoXZc/JULfH7cPr0N6Zf13hhRyK2gfto3AsUJJ9xqRIcN2CpdUoKt81we3pp6CcjnIIxoWRW/2E5ExNzSCesDw6rpAVcQm4D8It2lntAh8XEmKqTJuC+Ril3ReZarE=,iv:4zeCnCIlq5i0Ad5Ci0z+AwOwPucSZlh1Xm9BqD+E33M=,tag:OAvJstvvYA0qPphvBf/rGg==,type:str]
    version: 3.13.1
