apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: prod
stringData:
    postgres-password: ENC[AES256_GCM,data:MwxEN5u55jDXAcbi0KzPVIuyyk2CIuwqmQ==,iv:8Zxc4NgDppqK76J7zdY6yBb34sOOpRm7O6K/dng4V3E=,tag:ufKvz2u7okMFdZrvnRKYWA==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPeUNGUGpPc1ZvYlJIUnpv
            MmNndXY2L1JmeWpGVWZSWU5oMk9KYjE0djJjClo0ck04V2VvczNvMUxLSGkzM0Nk
            Ly9VZGd5VXNUbkNVbUZVNVAzNjdqTUEKLS0tIDcwTUFoQmlCdC9EUDRpWDhLR29H
            NWxRdndkRzBIL1pSTkhZVFIrU1ZDVm8KT3VMPQ7qV93G1pJ+QCMac7MmWSJ+M2VL
            0yvs794VFgi70Ez+L7srfx7X2SGjgaPCm033MnMKxEpbABl7eS4Xfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T05:22:25Z"
    mac: ENC[AES256_GCM,data:FBg0GQ2LsrRK5xOsfhOJeW0psqDKCu70Oa593rsKnuZIm3kX8b9VFmipueFnIsj+GRSevDQ3DHYrzTq3jN+JjYy07WMgNpNke4KjnbcqdINGNe7HbxhmR/1yIL6tzXfEY9nMh12RxB719R2jRE6OmyQJbB5Uz42JX4myZGD/yX4=,iv:mQ9O8uVTOz1oZm3RvnuWuTCmMlZkqhz8QnTi9Bk0Q34=,tag:t8vkwxmLifku6UUgbvSyXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
