apiVersion: v1
kind: Secret
metadata:
    name: grafana-mcp-credentials
    namespace: prod
stringData:
    GRAFANA_API_KEY: ENC[AES256_GCM,data:LAu07j4cea1o61S+kji/yyug+pEculNIP05bfmAjljM4MlwRQIfRtoVZbiKEgQ==,iv:wR9aniFX7F/53+l4yeJnXkiDockmLyacgI9aGUhcdTQ=,tag:sLlDiDTG6de50Bi/AMbi3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYUpaL1UvaTlVMlFRbVRn
            bXJ4S0Q1UDlQNWpTa2Z0ZWlGWXcvTU54SlJNCkxQWTM0UVM5N1owSHpjRnd0aGtP
            cGhjZURsZGJYRytJR3g3bVhHSVQycFEKLS0tIGlmcmdkZ1RlNHhhTVpsazJNNzdR
            VmJtMnBlbk5TN09PT0JSTDN0cXg5ZG8KOelWZw70KS79080TXc0bzzCr3OqsnTtq
            /95gRJh+8kJaf9NoqoIH1AQN84vOAb0chSjG1EFrnEsrnU+TV44yZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T15:47:00Z"
    mac: ENC[AES256_GCM,data:O1mEx1VBA75XLxpIdaPVhk5H0RQFsdWBASarlanPCwL08Jg6YYB1Z+7UtABO8I02/btQcxPaJc561swc+9dUsJAYukzcGe3Tin5qSCb3ht9jREBpuWJGvnrt0dvAvEs2mynkuKW8idgzk9yh9j0mgam5KOHNac1YazgIBeJL8so=,iv:lcF00Dcf44hUGXsKPHXYEjIFNioLdhT2qJYAY5EQQBE=,tag:ZxexJqnUtzdcYoY5x/jtaA==,type:str]
    version: 3.13.1
