apiVersion: v1
kind: Secret
metadata:
    name: grafana-mcp-credentials
    namespace: prod
stringData:
    GRAFANA_API_KEY: ENC[AES256_GCM,data:pwRRgNuz8ydxfU7yi6HqnrgHrW/uA6GS0+IjkTxk7sh3P4lDXhOdRg2xWqjmhQ==,iv:zlBRdn3Rt3LiatxXOFIYd3UPtteYz+qQp+Lb7x0uoHM=,tag:vyE2+k5Ad00w9G/J4qrfnQ==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYUpaL1UvaTlVMlFRbVRn
            bXJ4S0Q1UDlQNWpTa2Z0ZWlGWXcvTU54SlJNCkxQWTM0UVM5N1owSHpjRnd0aGtP
            cGhjZURsZGJYRytJR3g3bVhHSVQycFEKLS0tIGlmcmdkZ1RlNHhhTVpsazJNNzdR
            VmJtMnBlbk5TN09PT0JSTDN0cXg5ZG8KOelWZw70KS79080TXc0bzzCr3OqsnTtq
            /95gRJh+8kJaf9NoqoIH1AQN84vOAb0chSjG1EFrnEsrnU+TV44yZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T08:36:53Z"
    mac: ENC[AES256_GCM,data:XdAmWerO/La1YEbbAtrLnTw4z0Lh/eRwu20dUJWN51Yfqi5flWDgQ0BHjXdBWWI1O2KTUfckNp+1hU0z3yW74o0h3XgEmVI954e0sLQEZTnzOpIK9y3lYJEmIUskJmMNdqPkHg0iUTW+czzuuCD7ivqQ1W/riHIFeFN231gXDLE=,iv:c8SeUBEetP/dDtBpe53Ct3uge7DOQdDUU0IKw7GEVYY=,tag:xWceDSgNR/9lDobWBtw/8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
