apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-credentials
    namespace: prod
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:7VspIUvKPieTl36sbgzX1yJkxjwq1E4Hv0R+TaxJTw==,iv:lDwBaQd4Oe3EmUgBxI+qaaDsx0TUZvHnuhFSkI2UXqw=,tag:lgwN6g0fk9oInkIBFBOFLA==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:i3IGjxjczfjbxbAC8hUdK8v/jtM4/PKMCQ==,iv:FHXNxF8wQb02V+8D+FRycR1OGRDdsjZITlpbmmkGMsU=,tag:J+Xuw0Iy+7pW6XC6Nqi+VQ==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRHNBa2VuMk1oMkVRbzJY
            NWU4bjBRaXpxQkdPdCtqWjdUT3REeGVGYjFzCkRIcmRhbStRYS9tblV0VTlTdm1l
            VGV1ZzB0eVlLTjlRTFF4czF1djJQYzQKLS0tIG5sYXM5ZWhzSUFuOUFkMVBoejNU
            ZVZzdjdEMCt1aDl3aDNVRnFKMUFJdmMKjyhUZrkxQiP+dZrpbgMSSiWGiH/mYYm3
            dWfLeIp8JhmISEwgqFFSbMjtI4MPabZZZ6ZeM46aMmT55ZgWlQ6GFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T09:59:37Z"
    mac: ENC[AES256_GCM,data:i/UekUdvG2ZRga2EQvB7/GefDwru6mI7lQ6CbVueCtmyagpDbCKpwUV464j3kQ2ldZ22EY2GjGsz50wMu68in3sK23bH5/J14mn8vV92thb7+ksx8xY731QGb/i+waElvsWpiyqouxxvd2DjkEZOUWZkbwQJonKhW2v2qpWviTE=,iv:ITMu9Xu0UXJlb2jz0bJ323WaA7MMxjqSTJEJDVA4OVA=,tag:PhIIieqQv+ib5SpanTiQ8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
