apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-credentials
    namespace: prod
stringData:
    pgadmin_pw: ENC[AES256_GCM,data:v8P+AXcgFT3BnLn/oqG8aGHHn5liMo9HOQ==,iv:6QrljvhwTR+0FoHgYv2GqRdwV9nmkNZQqnLeVTbQfmI=,tag:5Tof/TAl9ikfntfselfJGA==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRHNBa2VuMk1oMkVRbzJY
            NWU4bjBRaXpxQkdPdCtqWjdUT3REeGVGYjFzCkRIcmRhbStRYS9tblV0VTlTdm1l
            VGV1ZzB0eVlLTjlRTFF4czF1djJQYzQKLS0tIG5sYXM5ZWhzSUFuOUFkMVBoejNU
            ZVZzdjdEMCt1aDl3aDNVRnFKMUFJdmMKjyhUZrkxQiP+dZrpbgMSSiWGiH/mYYm3
            dWfLeIp8JhmISEwgqFFSbMjtI4MPabZZZ6ZeM46aMmT55ZgWlQ6GFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T11:08:22Z"
    mac: ENC[AES256_GCM,data:ImZ2fbxWHSbEK5tG42w5/Qrxesw/VLFQ4Nwh4fJ7FnlkS3oOjTq2prBR9ogcDfcqs+J51Dj/OtgHrKJdl+Tj2aPnLWnw3fFghonhiAAAQI7C+Pquw+7Tk68ruqGHpW04ttX9Ma4KxGdcDZrQPoJutbKhlu4UnBl/gD52IwVjSvU=,iv:GVjqfTWZEly7H71XswPZTNwD5zxYBjmqQj/4Qtlw0Y8=,tag:Xxv04VLGzHQi8axpFcL53g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
