apiVersion: v1
kind: Secret
metadata:
    name: prometheus-grafana-admin
    namespace: prod
type: Opaque
data:
    admin-user: ENC[AES256_GCM,data:xjPPYflZ7Sk=,iv:B8Epu3QqDY3fUtsOyEzpqhePM9x+NpwD3Jn279E3hIk=,tag:Wc4uCRua8sCTMkosFHjY7A==,type:str]
    admin-password: ENC[AES256_GCM,data:uOtqWiPTGLcvE+nUtZjr1aZCEqSqA0VL,iv:4uj7PfvpeJV1sGW95IblSkmMV9zgmXAOiCK0MS6qVh4=,tag:EHd6d8Z6B4sn9JPwigGPHw==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycUxXRTJDcDRqaVdTMWdy
            ZHljbmVOUWo1bFBpc0dTM1dDaU5PQktPUndFCndJNGlVUDF2NXVYaHp5WGJ0aFBu
            cXFuTVdzcXJWUkhRZGRZTDVVQTdjWDAKLS0tIGpIOWptV0p3QTRQYWdRbDY0cDdI
            SkxGanpvdFoxTDFPSE9OQnNuR0YyRzAK7LCDkybupn7Rsv48oJTnkY32bS7BqJrZ
            KcGO5gWf5siwFU9X9Yq3QAd4TaDDG7IM7Kh58Ixl0uxMH3TulBjpKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T21:12:00Z"
    mac: ENC[AES256_GCM,data:PhjKuVZgkf9WNLtsOAJ5ODTCXogE7B+V8ez6xA/ySL+PhxtctGwglFVhwTZHspuXyKv1lqaAQyJjGVf3YVzG9VpjG46dBFADikfLS7glDIdN0BsXeeEH3w+nXFNT4mgHYxgYoqblupQGZIqVOOb7MgBWjoLUag7OKQf0spcpKe0=,iv:B50KOpHbFvk4NItntJ+nTEclvv4SoHLhziW1IRH2h4s=,tag:MVBNhBlImm15S+r3n9vrng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: prometheus-basic-auth
    namespace: prod
type: Opaque
data:
    prometheus-users: ENC[AES256_GCM,data:dzZZXDtyGWKphb2aSIWddJ2ctRa2fnvG1h2ijCBXybTQiHq76DkiIRrfimIE2tXKw43OHEQ2TGh6+P6B2VXKYdFaSPh5qK9v4IqknTonCAIgr1aWHk9oUXmZjnXkzjOY1AnPju7baVPHkfKuAMbYPsH3lYVrryKa2GeVe3s0OxqE97F9RS1eTZxXcXtsQ7Kwk6xslp4gIeluT5prGVTAOas+fsNX37cpeU3mTBWMcBjXDsMUisVObQ==,iv:xKl1APxhQFux+FuyYG4bc4j6HKnUfxWzIQbWSKLlARk=,tag:i++hjnt9fDmXpikf2kbtAw==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycUxXRTJDcDRqaVdTMWdy
            ZHljbmVOUWo1bFBpc0dTM1dDaU5PQktPUndFCndJNGlVUDF2NXVYaHp5WGJ0aFBu
            cXFuTVdzcXJWUkhRZGRZTDVVQTdjWDAKLS0tIGpIOWptV0p3QTRQYWdRbDY0cDdI
            SkxGanpvdFoxTDFPSE9OQnNuR0YyRzAK7LCDkybupn7Rsv48oJTnkY32bS7BqJrZ
            KcGO5gWf5siwFU9X9Yq3QAd4TaDDG7IM7Kh58Ixl0uxMH3TulBjpKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T21:12:00Z"
    mac: ENC[AES256_GCM,data:PhjKuVZgkf9WNLtsOAJ5ODTCXogE7B+V8ez6xA/ySL+PhxtctGwglFVhwTZHspuXyKv1lqaAQyJjGVf3YVzG9VpjG46dBFADikfLS7glDIdN0BsXeeEH3w+nXFNT4mgHYxgYoqblupQGZIqVOOb7MgBWjoLUag7OKQf0spcpKe0=,iv:B50KOpHbFvk4NItntJ+nTEclvv4SoHLhziW1IRH2h4s=,tag:MVBNhBlImm15S+r3n9vrng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: prometheus-grafana-datasource
    namespace: prod
type: Opaque
stringData:
    datasource-password: ENC[AES256_GCM,data:iABnak0NYoiveyQhfaM4KjWlQ3rgVZpr,iv:uOrhaQpds2PE0Yeh+hqc0a9NUbZqMGwNZrYx18YcRpQ=,tag:AQJKpthgFSNBIK//lhReig==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycUxXRTJDcDRqaVdTMWdy
            ZHljbmVOUWo1bFBpc0dTM1dDaU5PQktPUndFCndJNGlVUDF2NXVYaHp5WGJ0aFBu
            cXFuTVdzcXJWUkhRZGRZTDVVQTdjWDAKLS0tIGpIOWptV0p3QTRQYWdRbDY0cDdI
            SkxGanpvdFoxTDFPSE9OQnNuR0YyRzAK7LCDkybupn7Rsv48oJTnkY32bS7BqJrZ
            KcGO5gWf5siwFU9X9Yq3QAd4TaDDG7IM7Kh58Ixl0uxMH3TulBjpKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T21:12:00Z"
    mac: ENC[AES256_GCM,data:PhjKuVZgkf9WNLtsOAJ5ODTCXogE7B+V8ez6xA/ySL+PhxtctGwglFVhwTZHspuXyKv1lqaAQyJjGVf3YVzG9VpjG46dBFADikfLS7glDIdN0BsXeeEH3w+nXFNT4mgHYxgYoqblupQGZIqVOOb7MgBWjoLUag7OKQf0spcpKe0=,iv:B50KOpHbFvk4NItntJ+nTEclvv4SoHLhziW1IRH2h4s=,tag:MVBNhBlImm15S+r3n9vrng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
