apiVersion: v1
kind: Secret
metadata:
    name: prometheus-grafana-admin
    namespace: prod
type: Opaque
data:
    admin-user: ENC[AES256_GCM,data:auTiXfoVLoQ=,iv:j3kSmp+u8qa4QoUgdr4NHpjp5qG9DRcjSXO21sdl6hk=,tag:jztT8H2avuKPfJ66nDDL/g==,type:str]
    admin-password: ENC[AES256_GCM,data:uOtqWiPTGLcvE+nUtZjr1aZCEqSqA0VL,iv:4uj7PfvpeJV1sGW95IblSkmMV9zgmXAOiCK0MS6qVh4=,tag:EHd6d8Z6B4sn9JPwigGPHw==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycUxXRTJDcDRqaVdTMWdy
            ZHljbmVOUWo1bFBpc0dTM1dDaU5PQktPUndFCndJNGlVUDF2NXVYaHp5WGJ0aFBu
            cXFuTVdzcXJWUkhRZGRZTDVVQTdjWDAKLS0tIGpIOWptV0p3QTRQYWdRbDY0cDdI
            SkxGanpvdFoxTDFPSE9OQnNuR0YyRzAK7LCDkybupn7Rsv48oJTnkY32bS7BqJrZ
            KcGO5gWf5siwFU9X9Yq3QAd4TaDDG7IM7Kh58Ixl0uxMH3TulBjpKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T16:31:18Z"
    mac: ENC[AES256_GCM,data:9S38iNSA3EIecN0txNxQgDWVfFIFJqIJ32X0m0yEeOPSXQN/4jbsNL7tj03H2Z5TdyRsV05jmInHyvgCQ4nmEve7bK1SwoQNzxa9Ai+eOoU/EiasGIwgF/Dts1L/HDlwsQbC89GFeomhpFJDwclf2lYW5PluZMeSFmwKZJUI7lc=,iv:lJw9ls+EB6IwDsaaKJMVR77b3dcY/0Vi0lQi1d6Olls=,tag:zxujlnpjSE/Ej/YCxoTm3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: prometheus-basic-auth
    namespace: prod
type: Opaque
data:
    prometheus-users: ENC[AES256_GCM,data:dzZZXDtyGWKphb2aSIWddJ2ctRa2fnvG1h2ijCBXybTQiHq76DkiIRrfimIE2tXKw43OHEQ2TGh6+P6B2VXKYdFaSPh5qK9v4IqknTonCAIgr1aWHk9oUXmZjnXkzjOY1AnPju7baVPHkfKuAMbYPsH3lYVrryKa2GeVe3s0OxqE97F9RS1eTZxXcXtsQ7Kwk6xslp4gIeluT5prGVTAOas+fsNX37cpeU3mTBWMcBjXDsMUisVObQ==,iv:xKl1APxhQFux+FuyYG4bc4j6HKnUfxWzIQbWSKLlARk=,tag:i++hjnt9fDmXpikf2kbtAw==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycUxXRTJDcDRqaVdTMWdy
            ZHljbmVOUWo1bFBpc0dTM1dDaU5PQktPUndFCndJNGlVUDF2NXVYaHp5WGJ0aFBu
            cXFuTVdzcXJWUkhRZGRZTDVVQTdjWDAKLS0tIGpIOWptV0p3QTRQYWdRbDY0cDdI
            SkxGanpvdFoxTDFPSE9OQnNuR0YyRzAK7LCDkybupn7Rsv48oJTnkY32bS7BqJrZ
            KcGO5gWf5siwFU9X9Yq3QAd4TaDDG7IM7Kh58Ixl0uxMH3TulBjpKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T16:31:18Z"
    mac: ENC[AES256_GCM,data:9S38iNSA3EIecN0txNxQgDWVfFIFJqIJ32X0m0yEeOPSXQN/4jbsNL7tj03H2Z5TdyRsV05jmInHyvgCQ4nmEve7bK1SwoQNzxa9Ai+eOoU/EiasGIwgF/Dts1L/HDlwsQbC89GFeomhpFJDwclf2lYW5PluZMeSFmwKZJUI7lc=,iv:lJw9ls+EB6IwDsaaKJMVR77b3dcY/0Vi0lQi1d6Olls=,tag:zxujlnpjSE/Ej/YCxoTm3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: prometheus-grafana-datasource
    namespace: prod
type: Opaque
stringData:
    datasource-password: ENC[AES256_GCM,data:iABnak0NYoiveyQhfaM4KjWlQ3rgVZpr,iv:uOrhaQpds2PE0Yeh+hqc0a9NUbZqMGwNZrYx18YcRpQ=,tag:AQJKpthgFSNBIK//lhReig==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycUxXRTJDcDRqaVdTMWdy
            ZHljbmVOUWo1bFBpc0dTM1dDaU5PQktPUndFCndJNGlVUDF2NXVYaHp5WGJ0aFBu
            cXFuTVdzcXJWUkhRZGRZTDVVQTdjWDAKLS0tIGpIOWptV0p3QTRQYWdRbDY0cDdI
            SkxGanpvdFoxTDFPSE9OQnNuR0YyRzAK7LCDkybupn7Rsv48oJTnkY32bS7BqJrZ
            KcGO5gWf5siwFU9X9Yq3QAd4TaDDG7IM7Kh58Ixl0uxMH3TulBjpKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T16:31:18Z"
    mac: ENC[AES256_GCM,data:9S38iNSA3EIecN0txNxQgDWVfFIFJqIJ32X0m0yEeOPSXQN/4jbsNL7tj03H2Z5TdyRsV05jmInHyvgCQ4nmEve7bK1SwoQNzxa9Ai+eOoU/EiasGIwgF/Dts1L/HDlwsQbC89GFeomhpFJDwclf2lYW5PluZMeSFmwKZJUI7lc=,iv:lJw9ls+EB6IwDsaaKJMVR77b3dcY/0Vi0lQi1d6Olls=,tag:zxujlnpjSE/Ej/YCxoTm3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
