apiVersion: v1
kind: Secret
metadata:
    name: prometheus-grafana-admin
    namespace: prod
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:4lLBXzyXIScCxumRvbMR+NVQpv3gVkShY/ZRGn9mlhDbJyedZwDqJ9AagouzLlRhGkpkDa9zCOaKajmkBWujT4zMgk9CrPaYcXq2oB8Gu6Y4BlODuk6aHZvq7fo=,iv:YfaxXbfykEkpUEuLsV94T6wxfMxxCbeSKNqexN/xtfU=,tag:NJBvcz44bDE2Gp3AQQ04ug==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycUxXRTJDcDRqaVdTMWdy
            ZHljbmVOUWo1bFBpc0dTM1dDaU5PQktPUndFCndJNGlVUDF2NXVYaHp5WGJ0aFBu
            cXFuTVdzcXJWUkhRZGRZTDVVQTdjWDAKLS0tIGpIOWptV0p3QTRQYWdRbDY0cDdI
            SkxGanpvdFoxTDFPSE9OQnNuR0YyRzAK7LCDkybupn7Rsv48oJTnkY32bS7BqJrZ
            KcGO5gWf5siwFU9X9Yq3QAd4TaDDG7IM7Kh58Ixl0uxMH3TulBjpKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T15:31:15Z"
    mac: ENC[AES256_GCM,data:UB59ShemH0Ye9i2Apd5EtUBF0T1wZDPelwAbPjT1fn/YgW5lCKCH59625+jQuA/SFhCgbD6SgE6WsbCtyJEkLd3my/g2PCf8VV/NCMyy+XQf41PvjPtMHFZMcrpLXnug+Gr3obIlSUSYfha/qwXHjOGfhEOTrt+q07If+Lq5CWY=,iv:w+u22JHk/Vim3dlZ5VNwBGPg2PIWPoykglE7Vr1XzBk=,tag:Jv790aU2poFVwMfNc0ufOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: prometheus-basic-auth
    namespace: prod
type: Opaque
data:
    prometheus-users: ENC[AES256_GCM,data:IwDOMPDGyWjPOca/lT4EuiGSiD3SO4QZUoACKUE2oT5cS/FH/w97I7FgezGATN9xWp7tHoUEACqrltUw+Kzbba7pwQqbywdRDhJ50A6biHCAPoI70ICPMUJIkhC1V3ZZAeT+rdgID8C1Wy2dQzq4cMZPeQgBl2fGiOWt7No+MXIQnHX/5gJW+mfmCKc0PVfedDXV6aurZGHcIgFVY8+nMoobVZn711k0ZQPCWZ9NCwOvHrRGawq7jA==,iv:Cvu/dfSz5i18W1wNeKbkEgKSKUIy/Cr1J/lqE6P/KsE=,tag:HTLfe30yNFxnMJAQ7vuM4w==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycUxXRTJDcDRqaVdTMWdy
            ZHljbmVOUWo1bFBpc0dTM1dDaU5PQktPUndFCndJNGlVUDF2NXVYaHp5WGJ0aFBu
            cXFuTVdzcXJWUkhRZGRZTDVVQTdjWDAKLS0tIGpIOWptV0p3QTRQYWdRbDY0cDdI
            SkxGanpvdFoxTDFPSE9OQnNuR0YyRzAK7LCDkybupn7Rsv48oJTnkY32bS7BqJrZ
            KcGO5gWf5siwFU9X9Yq3QAd4TaDDG7IM7Kh58Ixl0uxMH3TulBjpKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T15:31:15Z"
    mac: ENC[AES256_GCM,data:UB59ShemH0Ye9i2Apd5EtUBF0T1wZDPelwAbPjT1fn/YgW5lCKCH59625+jQuA/SFhCgbD6SgE6WsbCtyJEkLd3my/g2PCf8VV/NCMyy+XQf41PvjPtMHFZMcrpLXnug+Gr3obIlSUSYfha/qwXHjOGfhEOTrt+q07If+Lq5CWY=,iv:w+u22JHk/Vim3dlZ5VNwBGPg2PIWPoykglE7Vr1XzBk=,tag:Jv790aU2poFVwMfNc0ufOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: prometheus-grafana-datasource
    namespace: prod
type: Opaque
stringData:
    datasource-password: ENC[AES256_GCM,data:9eXUhmNHiqn3KJSvK1gFvhEoDOlGPV4=,iv:HzBLaFtay8klmNHOKNpUQnsuLOeV14u0zwX+gZ+CRRA=,tag:mz6SeCo4OCYIFCf/WhTWLw==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycUxXRTJDcDRqaVdTMWdy
            ZHljbmVOUWo1bFBpc0dTM1dDaU5PQktPUndFCndJNGlVUDF2NXVYaHp5WGJ0aFBu
            cXFuTVdzcXJWUkhRZGRZTDVVQTdjWDAKLS0tIGpIOWptV0p3QTRQYWdRbDY0cDdI
            SkxGanpvdFoxTDFPSE9OQnNuR0YyRzAK7LCDkybupn7Rsv48oJTnkY32bS7BqJrZ
            KcGO5gWf5siwFU9X9Yq3QAd4TaDDG7IM7Kh58Ixl0uxMH3TulBjpKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T15:31:15Z"
    mac: ENC[AES256_GCM,data:UB59ShemH0Ye9i2Apd5EtUBF0T1wZDPelwAbPjT1fn/YgW5lCKCH59625+jQuA/SFhCgbD6SgE6WsbCtyJEkLd3my/g2PCf8VV/NCMyy+XQf41PvjPtMHFZMcrpLXnug+Gr3obIlSUSYfha/qwXHjOGfhEOTrt+q07If+Lq5CWY=,iv:w+u22JHk/Vim3dlZ5VNwBGPg2PIWPoykglE7Vr1XzBk=,tag:Jv790aU2poFVwMfNc0ufOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
