apiVersion: v1
kind: Secret
metadata:
    name: grafana-db-credentials
    namespace: prod
stringData:
    grafana-db-password: ENC[AES256_GCM,data:z1MrYdeYAMnuno3I3S69JgDy3EZA0nNsPDTpoyIyHQ==,iv:W3p78fvihUgH0IpvlZ5sCmeXOdB1SrvY+h/DGhKCuXY=,tag:Z39rDxeaCT+vbhVbj9Vo0A==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Q1pveGQ2aW5hUzQrVXlw
            aU9mUEdxUkVsbkdQQXQ3bXdwQ2I0b2psOFVBClpRc242eVVyY1BhNXdrNWt3VDhh
            MXFzNTVPelNsdWR3K204UDBYYTRHeEkKLS0tICtqRFlVWVZneEtrNzlkNFVmQzNH
            V01Dc3had1owT2NQMEd6b2dnWHdwMDQKkeB8rOgaSkNB+ibEsjPc2JRpwINGOfKV
            QqhCvJzYuhzwuEg6yQW78Ax1dvf0XGE0VwLDK6WlNg7Ez2iYfSqGLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T14:39:05Z"
    mac: ENC[AES256_GCM,data:lkpsh6HpEd51fqLchgoine95D9xfcW3uXJAsQqDjpNpoYemkvzdj2T/YaHtQ3TxWWT1iNBkrNSAO0nmC8e3bHERNkhhi6ofoMwQVFWNakr2fTYEGRNg0tqazdNRTlJWI4wxHa90Fv+BUKzmSSOuFuf7gmXqMzoFg4or5TzyM+pc=,iv:Za1WllFstMcSKNt2KRX3gWSZNUa+l3DbSzJo2wlDU3Q=,tag:2e4Lf6jekPXmDqcO474TdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
