apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-minio-credentials
    namespace: prod
stringData:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:NdTZrodObDkqmEtjKWg=,iv:O8CFeEkcfdaXJ+gmKmG3m6+V/Oitcd1hVmQ1DnwpjdE=,tag:J0ozrqa+aY3xWop50mHGhw==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RnhWcDF3L3dTNE1OQTlE
            ZlNWNVdsOHRLQll6N1E3aU1zVFc3RHU4MEc0CklaT1p1NHF6WHZwQzZpbGtFNmEr
            RHFTdk5INnlBTXVMOWlhVk5ZdGcwek0KLS0tIGdMTmdQRFFXckljdHc0WFJEY1Zn
            N1BzajF5cmFhMmVvU1JOaTFibklJaXcKaG0D/cBzsrkknEXzeMEFWh0rgiCxUWC6
            iV4CQwkgEiZ9Y+UfBoOk9pnybkKuRJewcuI0ZErdEjSsURGTj7lgGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T23:54:59Z"
    mac: ENC[AES256_GCM,data:i7EtKRroJ4Vnh1lweMjjOaw1pyEFw4/GWzeiu2gyvvv4JGZjNllys/JFnrvn94srs4+2CWrxfHJIFXeY3TT1nQ6NpelmQZbVQvlVamv9jXey0xKrI/XIMJnU7HV4kfSq+JVJ39NlLircwB2bmMCQUC9SFOiUtFV+8M3D/TRK6pY=,iv:MaTsolvqjkqjKwB90Oq8Z2CtCoxKg0ShMg4J2KU1mKE=,tag:7f7d95B/tLp7ewu0HXDbvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
