---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networking/gateway-api
  - networking/metallb
  - networking/nginx-gateway
  - security/cert-manager
  - storage/democratic-csi
