version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: add36o.y5ggex57hqb8ed8b
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBbUgxU2lrS0E5T3BVQ0lzblp3TUZKekFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qWXdOVEU1TVRjMU5qSXpXaGNOTXpZd05URTJNVGMxTmpJeldqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUJyT0h3cjIweXpCbGVPR2RXWnRtT3JWTVNSTFZCMVJCLzZOCkl5U1NkL0FJbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRk8wMWZFSElMZ2wrdkNhOApFeTYyRm5tUThhbWpNQVVHQXl0bGNBTkJBQnNUTXV0dGRmQ2lDdU5JT001Zy9IT01RRUV1RGNQUmF4R2Z0SlNKCmh1M3FNeU0zdDJYTDZFWm84QVVTMmhPeW05Z1RmY2IrTldPUVJtQkhSa01jVWdnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJSUpqa2o2TUNUeFVpQ2tuZnNCZTFoNmkrOXVDSmxzN1JCbzlJZm95NURuSgotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.36.0
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v1.13.2
        wipe: false
        grubUseUKICmdline: true
    features:
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
cluster:
    id: lrlG2oG8xmJGgJFMiQZ6qFzRoXznQNTwlqCK6B0t95E=
    secret: PuBvD2ts43EtwL2qOsJStNgyB0vBh04EPYUE9pduAkw=
    controlPlane:
        endpoint: https://[2a01:4f9:c014:30cf::2]:6443
    clusterName: hcx1
    allowSchedulingOnControlPlanes: true
    network:
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: xi7ykq.j0lwwma9q4x0n0u7
    secretboxEncryptionSecret: qrXKZkCnbQyWLu5XhnNIWA7b+lYLSQW6bqWNZEK3AlY=
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQVMrZ0F3SUJBZ0lRQXBYMFhwSnE3Nm1YblB6YTg1QXJ4ekFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTJNRFV4T1RFM05UWXlNMW9YRFRNMk1EVXhOakUzTlRZeQpNMW93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCRVA0eWo5M252WnJrblJGaWZCcUIvdkhSaDl0L2RYVzE2bnJzeEF1UFhNYW1LZnRGMWVEZ3JFcU5iMEYKTElmbzVka2R4VEVxVlpDV25Tb1U1U3RIaWtHallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVU3K0tXb3dEaXhpMFcyTWVUbytqS1ltck5tOW93Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnU01NRU8yOTkKTHI0eUI0RW51ZFMwcHo1UXBPcUF4Um1aMC9vTjFZemxoTG9DSUV5OXo3OGI2aWRmOE1yLzhYWVpLYTZVSWJiUgo0b1A4bXZKekUvcUVOZFJSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUd0QU9DM05uK0Ywc0hON21QeGJJZnl2NGw4RDh1MkFIY3QvVHhPZVNkUkFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUS9qS1AzZWU5bXVTZEVXSjhHb0grOGRHSDIzOTFkYlhxZXV6RUM0OWN4cVlwKzBYVjRPQwpzU28xdlFVc2gramwyUjNGTVNwVmtKYWRLaFRsSzBlS1FRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    aggregatorCA:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJZRENDQVFhZ0F3SUJBZ0lSQUtJOGx0OVM2MGtuYm15N3JHQXN1aVl3Q2dZSUtvWkl6ajBFQXdJd0FEQWUKRncweU5qQTFNVGt4TnpVMk1qTmFGdzB6TmpBMU1UWXhOelUyTWpOYU1BQXdXVEFUQmdjcWhrak9QUUlCQmdncQpoa2pPUFFNQkJ3TkNBQVF5VTlYb25VZUgrcmlaVWlzdmdaSExvT29GQ1A5bnYxVG5GNDhPM1o4T1dQM2NPL1h3ClpYYjRmR092cVBKWmtFN2ZxT0tOVU42OGtyOG8rQUtGdzRYU28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXcKSFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpIUVlEVlIwT0JCWUVGTE14WW4wdEk0R0hCWkVuaW0wUmpvdDZQdUZoTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDCklBRkptT0tObnRWUWRhWXdNU24zMW9hQllDSm5wM0dpSTVWRGJBMlZuYnYzQWlFQTdxazN4N1ZzaHFCQzdOUkoKMUJxVjhoK25iZkxOSFNoYXd0Y0JNVXViYVZnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUJZbnA1ZUg1NVhiS0NERDI3WElDdkNzejV1OTlrU3JZOTdxVW82UlcrUDlvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFTWxQVjZKMUhoL3E0bVZJckw0R1J5NkRxQlFqL1o3OVU1eGVQRHQyZkRsajkzRHYxOEdWMgorSHhqcjZqeVdaQk8zNmppalZEZXZKSy9LUGdDaGNPRjBnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    serviceAccount:
        key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBeWUvV3Q2NVF0Nm0zMmxoQnZVY3V0T3YxSG9RRmJXQlBBcmRLeXJobzYyVFh2TmhFCmdURUIveVV3Z0lKZjRCSWQ5Rkprb202WC8ycU1sdGh1TDhYZ29sR1c2QzVISkRnbXgrQzVZWDBtYTRML0ZKUFEKVStVc1M5SWdibzIza1N1Vm5yWC9iNlZWSlE4SDdWcVp6MVcycFdRRXBaMWpKY3hSQjJNYkNVMjdOM3p2K0MzdQpiWjBIMjFIOThacjd6QjdocU9iU2hWVmYvbVViQ1NuNzNURnY3Q0ZPcjZVejhkemtHWTZ6UXJJZVdPNXZXVWJoCkV6cXpMS2puQmNtWDQ4bXR3Z2RRR3FJSklTbEliT2FXN1dDUFVpRzlaR2VjR0ZrWU01cVVVa01nOEY3L3ZYU0QKUjJ5Q1hzVmwwL0Z3KzM4RzVpWG1TTlR5bGh4WU1iMFIrdlZOTjY5dW80YzRsMHpJL0Vnak4yblpOQ3E0YmtvRAowY2dyRzIyaDhwNUFDRXVhdE1ncXdTMlgxcVZEcXo4N3hFdWRsNXFJVVI1TE1tUy9laWI4NVcvSkxnM1Rnc1VKCmVuT2lvaTVRSXNwUHBXV2VpazBNZHdzSWVsaFNNMUUydG96UXZyaHRtWGFlN2N6aDNQaUtsRDBDOTdnbWxKTk8KSjdUemt4Zi93V0xEcDVZUG5paTBkazVKK2lONHQ1WTFoV2lSdlZ5SGRtdy9mempIRjdnS0RMM243Nld2UlVYYgo1U04xYm4yTDlzbU1VQTBwNnFuaVVyRlZISjdIdFA1dHhhMkZCa3dOVWFWYkIycHlMMmNtQUUzQXpMUEt1Y1NMCkZHNUpGMmFydnozaWUrRDVmencvNG1CUDhXVzVzWW82MmRRTTlIaEt0YXZMRTRZN0FsNktpaTNpdDVrQ0F3RUEKQVFLQ0FnQlFnOWJlWE52bEp2L2R5SlBKbHNDcU5XeUI4c3pCTEFYRXhQVkd0OWxwaGNjNURoZmVWUDZCVDBBego5UWVxTFQ4UlErckpFd1I2dSs1N1ZLYzJXQlQxVTBleW9vVU9EVzkxQVlhWXR0QWpUTk5NenBUaFpuNVBhdVF3CmdFUGhWM25zRW8vYTRaWjkxS3pwOTlaYzQwV1VVemxCR1d4SFRWdy9jRVgrNHlYUy9YY213cFdPMGU0b2hkd1YKUWFERTVjayswVzI5Nk9rQjR5a3c4Ykx4SWoySWJrMVQzakJFYnJqcDhjcEt2UDg1b1RQM2FqbmlzMlJ1V1pmbgphRll0NWlOb09nYzMzMFI1bXQ2OFFRS0xlaFVhLzhYbWF5TkRWLzY4MEpUejZiMFA2aWpZenNSckxYb2J0R1FoCjZlSU0vTHh3OWtxSDNwUXN3dmR0T1lBYVNrVXpTZWt0SkM4Mk5POEJPVXNXN1hjY05YOGQ1bU1Eb0NmUWlnL00KUGR0OHlYZFQzbU9lZFAwSXdCMTdkVUQ5Zzlnc21yRlhXdzMyUkN4YjFCOWpSMjNIT3E2bmVlUGdSMTdEenk5WQp1U291VzdXODZiN2lRRW45T1czSWlzZzNVNHhjdDhTRFBCOUdsRDd1MzAvVCt6dmV2NkhIaHhSQ0V5U0lRL09pCmpBWi90enJhNTc5OGx6bjIxMEhra2s0TlRsb1ZGTDBpUlRoMnhXMTN5ME9qUTN4NFIwbDkyc2p3TXdST1R4K3UKM0xkcVVSWWovcng5anMwYlYxR0FXVHkwbHZSaW5wVzMrcnltOU5HOUt2akxWUHovK3pHeUw0WmlJSnZTZmtyRwoybUFvOXNWSyt3czNOTHMxMklyMUU1ZlE0Q25OWWFHMUJmODBWRzZrOUc5cTRmRzlRd0tDQVFFQTR4ODBwSUp3CkQxZkZ0MVVKd3Z6QUd2b1dRclJ6aDIzeHBvN2dwaVl4TmVpajFQQUNEeWcraTRoY1hYOXYwNWg1Uyt4K0loajIKcE8wRWcreUNlb1VwM09RY3JDdG5zYlEzZWJPd2IxdWpIWkZkOW93WTlJOHJ6WjduZlNqU05XUWkvSGFER0VScgpIMUpiV2FjYlBCY1Z1cldJOTEyZzhLL1F0Zm1JcGdRZXZ2RlJaV3RMc283aW9ldlNpV0w4ek1aMXU2QkxkRHdKCi9xeUV3YXZXR3RBay9ISTFCbzBCMXFxQUJIRHlQcDhCU1VFVFcwOVJyL2pHMmgrWFJqcjQ5bWZOUnh2dkp4Vy8KeDM0TTBUbGdSN3Y2U0tMVjdLb2ZnRERFT2ZLZ2FyYUx2OW9mS09sVmtZZUdtK2tEb1E2VHZ4eGlKeHJ0aXVWSQpKTXcxSzFiMzFGUmcvd0tDQVFFQTQ1emM4ang5bEZIZHZRZmhZSHF4UnVIMDkyTEpJYUpUelpFTDdZTlhxbW1oCkF6a2hyaXdpZXowZURtUUw5b2JMNzNOK2tncjJ4YmY2YjJySGhCMXFLeFptSjgzdVcvNUpRbFVzc0ZnMlV2YmYKd295bktXbjVjaTd3ZE1hdWVhRHBiRXM3em5EU05HcDN1bXZIczc5RnU2alQ2aWtteHQxZk9SR3FIYjRrR0lDeAp5dzVOaUZBTFlVK2xTMWN5eHpYaG80bEp4dDZiVGRLaDl0UkRDZkc2VC9ON1d0Kzl4ZWhuRGhRWXFDaVFlOEFUCk03VEdzTm8xeStYeGRaYVdxS3gwTUQ5RkpaWktCdnZhOFhLMVg0NGFPVURQVDhFQW5qRDduM1B5aVVEWGFFcEwKSEpIZmlmTTZyRUowbFZPWUlIYlJzd2g2eWdWTEgwRWswc3VtNlA5UFp3S0NBUUVBaG9JcnJpWWw4YUE4MHlmRQp3VHJwRnREM3NBZW95Qk1mNDFHSTBEMmNOVjRTOFFBM1oveWdsZ2hyRTJCdXZQVDNHVFQxT29Kb1NDS3E0dXFHCkY4T1htRjlzYjdiQkVhZzJscGdKck5tcmo4NVF4THdSNTN5SEo1NnRZQjExNlBMbUdYaWlpUk8wRVhlMzdDK2cKWElVYmRGa2d4Y2Nva29LOWE1aGVDbHcwVFVjanVwbkIyZnp2VVpBVlB4Smx2MnpsdXZuaTFmTGN4SHd0bjNtQwpNcDBFMnBGVXdBMXdnazYxeEd1VHUreDFXWW4xeWNUL0R1V1o5d0p3bDhKRFFjTVYrc0FiY1oxYTErM1o3MnM0Cmp5TlB4Z2JTQlBoMzhYWndNQlYyVmR6SWhSWE1FSEdvSUtrUDJuUTBsd1RJRVkzZ3YySWVQbjB0cmNWVzA5VU0Kcnk1Tnh3S0NBUUJHWnV1VVpZOTJSQWd4QXZIOE5KY0cxTGMvbWFlYXBxb0RLSDBtL3Z3cnNyWmgxOWNLRjQ2bQp6ZFd4SDlMdmN1dzdhVjdaNzFnNitkZ1ZoRktvRTYwV0hMeUdUVlVQMFV4NW52ek9vc3BTeVJlWEJvaGg3K3gvCkcvTzJPd29XaHVZTVlBemtvdEx4OFlpTStlOXdNcFp3SUIxRURXeDRFRnIydlBjQWNpS2FEWnh3c1VEY0M5NHAKUUVoaFVGeGRiOVlXRGszcW5Fb3ZQUnBweldmYStKRG5UK2wweDBYY3BERFVFdlU1ZGlxU2pHdWtENk54YWwwLwpieVZMZU1PcThvU1JzOUJBZXdiMHVBd1ZxS1JmSlFZSmRYbHFNc2x0Skx0L3E0NTJVNzhNL0FYVmxXMHVMelNUCnVZNXo3Y0pkTUVOV2ZDWDJ2TUpxcld5bFl1YUNwUTI3QW9JQkFEZ1BxWXk3T21JMjRmRHN2anNUSWZkemZvcEQKRGZmRkNYOWYxUmZuTVNGMG9sTEVKci9SS3c0Q0YvdXJLeU1mS1VCbzdJa1dYTHBQOEt3dldDM0lPV1ZtSW1CVQpsS3c3L0VYMnlMTlZCZUhlY3VCWVpIdUpXQzA2Q29SNExtUHV0c2hrTDBWVko5dFk0MXRRNC8zZHFaZTBiSFQ2CjZoYmhjbmF4U1FENm9UNjBSdkl6VkdXaExYY1hscGdKMU5YVXpadkpIcVRHNlVMN2RHZ2VtdkJJa0Z3cm1zeXYKSFY3dUJPd2N6QklXLzYzMVFRUHNyZVVFNWRORWQ1ZTFucFBJcGEyMm1vbXVPdU9LYlhKRE41YW40YVk4Z3FLLwpUdEw0eTJjZElXY2RwQVFjeTB2aEY5THZKbldpZFVQbWdxTkZaSzRxeXZmOVdUY1VLdkdkaHpxRkdQWT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.36.0
        admissionControl:
            - name: PodSecurity
              configuration:
                  apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                  defaults:
                      audit: restricted
                      audit-version: latest
                      enforce: baseline
                      enforce-version: latest
                      warn: restricted
                      warn-version: latest
                  exemptions:
                      namespaces:
                          - kube-system
                      runtimeClasses: []
                      usernames: []
                  kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.36.0
    proxy:
        image: registry.k8s.io/kube-proxy:v1.36.0
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.36.0
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmVENDQVNTZ0F3SUJBZ0lSQUxqYjBJY0ZEU202bVpjRmwwRVVhUDR3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FWlhSalpEQWVGdzB5TmpBMU1Ua3hOelUyTWpOYUZ3MHpOakExTVRZeE56VTJNak5hTUE4eApEVEFMQmdOVkJBb1RCR1YwWTJRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTc3cwM0UrVWZhClhnand0MisrUVR3bnJudUIwY1lpKzJzdFZhTm1rekJKcEYxYzRpVHV3dzVUeElWbytuRzBFVkRLRXlvZnlOS24KUklsNlYzOVhWNy95bzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkVtTHNzdEl5eXgrCjVaOHNCTmNHNDRuOG9SUGNNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJQ25IajhrREt1bVRhTXAyZ2lYTVhreUQKemVIV0NVNXE0R3g4UU4yN3BUTFZBaUI1ZHdTcjdXUUxXVzFWN1M3NGx2Q3N0RzlPSUFQcXdkK1pTYVpFUU4wawordz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdzTnZoSm5IcUFxcjhIYUZHMS9aaWx0VG9YY25VZk9jQjRPdzFuVVRJZUpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFck1OTnhQbEgybDRJOExkdnZrRThKNjU3Z2RIR0l2dHJMVldqWnBNd1NhUmRYT0lrN3NNTwpVOFNGYVBweHRCRlF5aE1xSDhqU3AwU0plbGQvVjFlLzhnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: stable
