---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: prod
data:
  settings.yml: |
    use_default_settings: true
    server:
      limiter: false
      image_proxy: true
      base_url: https://search.va1.uk/
