apiVersion: v1
kind: Secret
metadata:
    name: truenas-api-credentials
    namespace: flux-system
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:aVEEk7rQPyqL117cS+c6sc8p4+y/oLCSF8h0BMHO6S9frzr6leGJ8WmqkOiq2+ZFaqT2Wc8wIRAPWdd6L22ThL+V,iv:1/+1nikoF+Ylgjp51WrTq6oTlCEbkImP1Fyy2/A/41k=,tag:yaxp0T+8EiTKO0TCI9f9+A==,type:str]
sops:
    age:
        - recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOE1GU0hSU1JBWjFqOHF2
            R0hTbG1CUFUrOWNUZkV2a2lCbUlBb3NPQUVBCkpCeVgvTEg4aG1NdlVaVHIzOGpr
            NkZvSXA2dW43Y1pSR2xCQVlYTGM2L0UKLS0tIC9CUHZDOUMrMnIwOHdQd0p1WUZE
            MkVRUkYyMHplempycVpUYXpTaFpwMzAKmfstYYzSeiSkURSy2GugYkvBBSULU+PE
            3sOQQSjWaFkC1kBSqjq+FJpFzZb16awrei29L8MbVLAKkalvTMwe4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:59:17Z"
    mac: ENC[AES256_GCM,data:K4eSlQItXp6VonnXSN2mE8WwgIiOS479qDBarr8KxvzgW/4RtbfEQFUOLHIsFuHtfdVZ8/QFsJJ82c9iO/gw5kd5zxwSeefbccniWV500SUIf/5ktsXS1TEHWYmq4Que9QZq2TaNh4watg7yTDw9VvH3WPzho+1Xe3wA1Vqktrs=,iv:NOYcB7eGBsvKGeI8Ut41/J9KmpjWo+gHYzWKA9O3ckw=,tag:p0sEr6dcBDGST6k5z2ruqg==,type:str]
    encrypted_regex: ^(data|stringData|apiKey)$
    version: 3.11.0
