apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: prod
stringData:
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:oeBm8MiV7HFZAHRMgf7aFQxoh7S3A79mHw==,iv:sCpdEoZaOENmRsFlJgYHZ0sjegMbfi3PiIBcVITCzUg=,tag:oc+2uqInGc2KuSz4KwYnng==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pMxKsgOVWr9wiiaPoSyAZZWKLqKWUD5CaUVouoErxw==,iv:GYs8lbr7NOpvORYNNdzFBW6tj/1M0LJWe3mcXyG7CSI=,tag:5SYbEBOA0mMJBjrN2cecxA==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:itXbM4sFebFRK2RaF9YRccZWIuKR7i4pWJXGzLXKDETJkwnDBNg=,iv:uHqc7Lraiy9dLu2YZzOpKhyVgu5fQ2X2jPXe7CxZerQ=,tag:qLId6c1HGdhW9WpIu2OE9A==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:/R6dZOxFmNVn8ryA,iv:LlfHPRDpFKU0hCMa3oziex/785U2M6YnUhIr30/yjH0=,tag:DCkeMsciUn7TE5Kl0fRAfQ==,type:str]
    S3_REGION: ENC[AES256_GCM,data:wlUWNqCfsvaXl6I=,iv:NDUVOsBjRE6XOPo4OgcEbuFgyMQxRx2MFl7tn7qnzC0=,tag:70983F7BbG9+4vSfSBsLXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWFVwUFpxeFZmODF2dVJm
            WThPYmk4MlY1MlAxaWcrcFNjOCsxa042ODFFCkpaRzBkQ1RQdlBWMzQ5NTZCYTVr
            SGhXdjR4d0ZMRFgvcWRybjJleXpCOW8KLS0tIGYwSzMyVVNsWlpkVTV3c0dOMDNB
            dDA3a0JCQzlLV2ZWT1czeVYvdU16K0kKdcoJqCtZyJSNMAncPWGygawdC7Z66lep
            ES7U/8lR2jJQ/UzYlOAgAGRki+p6on7YKfvWO42OBssdSKrzAdCJuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p0qkg3hk5uey8wpd8phg997fy38jxfds2yjse5xw22eej9gjsd0qfssfua
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T14:20:50Z"
    mac: ENC[AES256_GCM,data:NPudXm0B/doNJPD7H4GAb/k/QmxnJQx/0V7wSFHbyGjfsR87P3KEoPwqKLwLTrkQl10EtrePMjVudXXoXvEQSSVy1s2ZL+zZlNAB+MXyL0OCqz3eJpQxa9QnqhGlOm5Ug+YQVVJmQk59RWvAOtWbVi/xoHa/D7nZaRQn1A8vQbU=,iv:hyHMHi6fBuuBaNW8up6hMTxIIRIB7bRQ4w9UHgeDW+8=,tag:O+KzxXMaU2kcztLmB0kSUQ==,type:str]
    version: 3.13.1
